### ISSUE TITLE
Combine turn mode - backing too far

### ISSUE THREAD

**Issue by sootysax** [Courseplay/courseplay#1386]
So I'm noticing that the turn maneuver for the combine (this one being a TC5.90) seems to be backing up way too far and off the field..   I did 3 headlands (which should be sufficient) and still the combine, when doing a lane turn, is backing up and off the edge of a cliff in this case (or into a fence, getting stuck in a creek etc)

**Comment by Satissis** [comment]
An image would be nice ;) also with debug mode 14 active, which will show the turn line it self :)

**Comment by sootysax** [comment]
it very well may be that I need more than 3 headlanes..  

one side of field with 90 deg edge (3HL)
![2016-12-01_122327616](https://cloud.githubusercontent.com/assets/6591048/20804665/c6881fc6-b7c1-11e6-959d-54fb104f1d76.PNG)
![2016-12-01_122451659](https://cloud.githubusercontent.com/assets/6591048/20804673/ce5edffa-b7c1-11e6-9334-2db826cc2c60.PNG)
![2016-12-01_122333385](https://cloud.githubusercontent.com/assets/6591048/20804696/dcf8d89a-b7c1-11e6-8540-50e687f996b8.PNG)

the other side of the field 45 deg edge (3HL)

![2016-12-01_122251595](https://cloud.githubusercontent.com/assets/6591048/20804716/eabfa012-b7c1-11e6-84dc-fd5c729bccf2.PNG)
![2016-12-01_122406103](https://cloud.githubusercontent.com/assets/6591048/20804730/fa84d5d0-b7c1-11e6-9f29-f8371336ddf3.PNG)

**Comment by sootysax** [comment]
with 4 HL - difference on each side of field..

![2016-12-01_125756517](https://cloud.githubusercontent.com/assets/6591048/20805728/03bd4a3e-b7c6-11e6-9bad-e79aa132eb66.PNG)
![2016-12-01_125843383](https://cloud.githubusercontent.com/assets/6591048/20805731/05d7c24a-b7c6-11e6-977f-8829e3f99ca5.PNG)

**Comment by Satissis** [comment]
alright. I have an idea on how to shorten it a bit.
What I'm thinking on doing is that if it's an combine, then reverse a bit in the start, so the first turn circle will be allot closer to the grope that's not harvested yet. that should at least take off  4-6 meters I think :)

**Comment by Satissis** [comment]
I'm postponed this, since the combine do work, which some other tools don't.
This just means that fine tuning this maneuver will be done at a later time once most of the tools are working :)

**Comment by sootysax** [comment]
im noticing on playing with the turning circle settings that getting the right setting makes all the difference..  if you are in a windrower and get the turning circle right, its a perfect U and you dont even have to back up.  

I am now trying to make the turning circle as small as possible until the turn fails and the tractor spins in a circle, then use the smallest setting i can

**Comment by sootysax** [comment]
im noticing on playing with the turning circle settings that getting the right setting makes all the difference..  if you are in a windrower and get the turning circle right, its a perfect U and you dont even have to back up.  

I am now trying to make the turning circle as small as possible until the turn fails and the tractor spins in a circle, then use the smallest setting i can

**Comment by Azthek** [comment]
Did you already do some experimenting with turns? The big Case already does back up at the end, turns and then backs up again a little (the red line), works like charm.
![fsscreen_2016_12_04_13_14_20](https://cloud.githubusercontent.com/assets/13201782/20866094/00058b94-ba24-11e6-9b4d-4e853d4dbc2b.png)

**Comment by gec100** [comment]
except the header is going outside the field.

**Comment by Satissis** [comment]
@sootysax the v01.0022 have shortened the combine turn a bit more. Could you try again and give me your poinion if we need to try shorten it further. (Remember that it's for the 3 point turn so the small harvester is needed to test it ;) )

**Comment by sootysax** [comment]
It seems like the projected path is still quite outside the field edge..    but it may be due to the default turning radius (12m on this combine)..  the combine is quite capable of making a 9m turn, and when adjusted to do so, the projected turn path is much shorter.
![2017-01-17_091902394](https://cloud.githubusercontent.com/assets/6591048/22024094/cf09a292-dc96-11e6-9ac7-b6960c6858e3.PNG)
![2017-01-17_09242669](https://cloud.githubusercontent.com/assets/6591048/22024097/d12a92e8-dc96-11e6-8fab-e1f35276c531.PNG)

**Comment by Satissis** [comment]
I cant do anything about the turn radius ,except hard code it for that combine but I don't really wanna do that, since I would have to do that to all equipments then and also for mods

**Comment by Satissis** [comment]
Try out v01.0056 or newer and report back.
It's the shortest way I can think of making it so this will either is the last attempt to shorten it or revert back to the old way.

**Comment by pops64** [comment]
The new way seems to be missing sections of fruit :( but it does definitely take up less space
![farming simulator 17 1_29_2017 4_44_20 pm](https://cloud.githubusercontent.com/assets/10678220/22408165/356e479a-e642-11e6-9d69-8dc07bbef0b3.png)

**Comment by Zoochase** [comment]
The old way was more efficient.  My 2 cents.

**Comment by lcc1211** [comment]
I don't think this should have been closed. My harvesters are still missing sections of the fruit.

**Comment by pops64** [comment]
Isn't closed Just the issue that was referenced to here

**Comment by lcc1211** [comment]
Oh. So the closed above is referring to the one I opened?  That would explain why I didn't see anyone saying it worked or to try a new version.

**Comment by pops64** [comment]
Yep

**Comment by Satissis** [comment]
Should be fixed in v01.0067.
Try it out and report back.

**Comment by lcc1211** [comment]
I still have a tiny bit of fruit being left behind on a mod map with vanilla equipment. I'll try it on GCV with no mods except CP and see.

**Comment by lcc1211** [comment]
Works fine with standard map and Massey Ferguson with the 12.2 meter header.  Perhaps a mod or my modded map are at issue.

**Comment by Satissis** [comment]
Well it can be a bit hard to get it to follow the turn line 100% since there is allot of variables to consider like if an mod vehicle is setup 100% like Giants do.
The best thing you really can do is when you generate the course, you could set it 0.2 - 0.5m lower than the work width is, since that will make an bit more overlap and should help out in this issue.

Can we close here now ?

**Comment by lcc1211** [comment]
As far as I am concerned it can be closed.
