### ISSUE TITLE
Pöttinger MEX 5 stops mowing

### ISSUE THREAD

**Issue by AgroWillem** [Courseplay/courseplay#1431]
I made a track in field 8 (Goldcrest Valley) for mowing maze to chaff with the Pöttinger MEX 5.
Mode: Field Track
It starts mowing at point 1 and after emptying the kipper in the BGA it returns to the last point, switches on the mower but NO chaff is mowed anymore. It keeps on mowing without collecting chaff.

**Comment by pops64** [comment]
I believe the Mex5 unloading with a trailer attached was just happy bug we enjoyed in FS15 that worked fine #1362

**Comment by ThomasGaertner** [comment]
should be working, since I've especially test it prior release... what does the log say ? which tools didyou use ? How to provide a nice and sexy bug report

**Comment by AgroWillem** [comment]
Ok. I reworked it with a new game with standard Giants equipment en no mods other then CP.
Problem still occurs.
CP 500.00014
Mode: Field Work
Goldcrest Valley Field 6 (maize)
Deutz Fahr series 7
Pöttinger MEX 5
Agroline TKD 302
Log link: [](https://gist.github.com/AgroWillem/20bebddd91830a841fd74730f5387d11)

Still it not collects chaff anymore after emptying run at BGA.

**Comment by ThomasGaertner** [comment]
try again with v .020 or higher and report...

**Comment by AgroWillem** [comment]
Problem still occurs with 020. :(
I mentioned that the mower will not mow at all anymore in that field with CP. 
It mowed only before the empty run to the BGA, after that no more. 
When i place the tractor on another spot in the field and start CP, it starts the mower and tractor but no mowing/collecting chaff. Its only driving.
Also not when i make a new CP-track.

When i manually mow or use a helper it mows normally.

**Comment by ThomasGaertner** [comment]
check the vehicles.xml in your savegame folder. for the Mex5 there is a value : "foldAnimTime" . I suppose, its set to 1 in your case. change it to 0 and try again.

**Comment by AgroWillem** [comment]
Thx!, It works now after setting the value to 0.
What went wrong?
Can ik prevent this?

**Comment by ThomasGaertner** [comment]
you dont need to do something , its all done with the fix ....
