### ISSUE TITLE
Bug when mode 6 hits fill level at same time a turn maneuver occurs w/ unloading course

### ISSUE THREAD

**Issue by pops64** [Courseplay/courseplay#1500]
So, rare bug because as the title says it only happens in that situation which doesn't happen often but you can force it by hitting the drive now button has soon you hit field edge. If turn on field is disabled the forage  wagon will just drive straight into the wild yonder. If turn on field is enable picture below happens. Here is [Log](http://pastebin.com/3jsXK4Rn) and [video](https://www.dropbox.com/s/n6f0wbwvaltblqp/Farming%20Simulator%2017%2012_12_2016%209_38_45%20PM.mp4?dl=0) with 12 and 14 active, this is with turn on field disabled and using the drive now force. Not related to version 31 fix, tested with version 30 same issues. Can not test it with mode 4 drive now does not work. Thanks for reading. As always keep up the great work

![farming simulator 17 12_12_2016 9_28_26 pm](https://cloud.githubusercontent.com/assets/10678220/21125315/b064d618-c0b2-11e6-85e2-1fd73cd2d71e.png)

**Comment by Satissis** [comment]
Alright. I'll look into that tonight as well with the #1492

**Comment by Satissis** [comment]
Try v.035 or later and report back

**Comment by pops64** [comment]
modDesc file got updated incorrectly. Update this when I test it

**Comment by Satissis** [comment]
Fixed in v.036

**Comment by pops64** [comment]
Not fixed any more
![farmingsimulator2017 64bit 1_7_2017 4_26_45 pm](https://cloud.githubusercontent.com/assets/10678220/21745285/639bd73e-d4f6-11e6-88f4-95eb87f91c4b.png)

**Comment by Satissis** [comment]
yes please. an save game with the courses, would be nice for this.

**Comment by pops64** [comment]
Ok. Took a while because of such the rare occurrence of this. The course you want is 0F15StrawforSatis. It should hit this bug at the end of its current row. I have had it 4/4 when it tried it. It has nothing to do with my mode 6 alterations #1362(Tested without). Here is the [log](http://pastebin.com/f8tYLN8n), [savegame](https://drive.google.com/drive/folders/0B5ZZXJetOeMRM2UxQy15MmU2aTA?usp=sharing), and [CP Courses](https://drive.google.com/drive/folders/0B5ZZXJetOeMRTldjSEpqSEFXSkU?usp=sharing). The picture of the bug you should hit
![farming simulator 17 1_9_2017 1_04_50 pm](https://cloud.githubusercontent.com/assets/10678220/21777708/f5f2dbe6-d66d-11e6-87e9-fa4535bc17e8.png)

**Comment by Satissis** [comment]
Fixed :)
