### ISSUE TITLE
Plow gets folded when it is not allowed by the game

### ISSUE THREAD

**Issue by ntrrlz** [Courseplay/courseplay#1662]
With the Amazone Cayron 200 the game only allows it to be folded when it is rotated towards the left. When it is rotated to the other side the fold button is disabled. When courseplay folds the plow it will also fold it when it is rotated to the right. But when you try to unfold it you can't because the button is disabled. The only way to unfold it is when you let courseplay or a hired worker do it. And then after it is unfolded the game is still a bit confused about the state f the plow because it is rotated to the left, but the fold button is still disabled. When you then rotate the plow it will rotate halfway and then rotate back. 

Can you make it so when it tries to fold the plow it tests that is is allowed.

The Lemken titan 11 has the same issue.

**Comment by Flitch49** [comment]
I also have had this problem with the Cayron 200 plough where at the end of a course, Courseplay folds the plough ready for transport but there is no unfold button to allow the plough to be unfolded and dropped from the tractor.
My solution to this problem (temporarily I hope) is to reset the plough back to the shop.  Upon picking up the plough again the fold button is re-enabled.

**Comment by Satissis** [comment]
Should be fixed in v01.0072.
Try it out and report back.

**Comment by Flitch49** [comment]
Sorry to say this is not fixed yet.
<version>5.01.00072</version>

If the course finishes with the plough angled to the left, all is fine.  If the course finishes with the plough angled to the right then the fold/unfold button is still disabled after the course ends, both the Cayron and the Titan suffer from this problem. the salford is always angled to the left so does not seem affected. After finishing a course with the plough to the right the Cayron cannot be dropped as it has to be unfolded to allow dropping. The Titan can be dropped as it can be dropped in the folded state, but on recoupling to the Titan plough the unfold button is still disabled so unfolding to continue ploughing is not possible.

Ploughs tested:  Cayron 200, Titan 11, Salford 8312

**Comment by Flitch49** [comment]
Tried  v01.0072. and was dissappointed to find this was not a fix, then noticed v01.0073 was in the updated code for this. 
 <?xml version="1.0" encoding="utf-8" standalone="no" ?>
  <modDesc descVersion="34">
 -	<version>5.01.00072</version>
 +	<version>5.01.00073</version>
  	<author><![CDATA[Courseplay Dev Team]]></author>
  	<title>
  		<br>Courseplay</br>

**All working fine in v01.0073**

**Comment by pops64** [comment]
Yea the version # got skewed. Closed to keep issue area clean
