### ISSUE TITLE
helper in fieldmode loses turnpoint

### ISSUE THREAD

**Issue by 3lronMcBong** [Courseplay/courseplay#1878]
Hello,
When i start fieldmode and the helper is the end from the field, the helper will not turn in the other direction.
Helper drives out of the field.
This happens every second row.

thx for help :-)

[log.txt](https://github.com/Courseplay/courseplay/files/836006/log.txt)

**Comment by pops64** [comment]
Picture and log with only debug 12 and 14 active

**Comment by 3lronMcBong** [comment]
yes this is the bug i have, how to prevent this?

**Comment by pops64** [comment]
Avoid using the Opposite turn direction option until we fix this.

**Comment by Kattebakke** [comment]
I also have this bug. Thought it was because of mods and maps that might have conflicted, but I tried with a vanilla save-game with only CP activated, and it still happens.

**Comment by sootysax** [comment]
I am having a similar problem when plowing with 2 headlands.. the 'turn on field' will work only sometimes, especially when there are two tractors working the field it seems..   even if it is 'activated' the tractor will turn outside the field, crashing into trees and rocks on the edge of the field.

**Comment by pops64** [comment]
@Sootysax Hmm that may a different issue all together.

**Comment by pvajko** [comment]
It seems to happen only when "Turn on field" is activated. Here's a screenshot what happens (Note that due to an already fixed bug in my course generator not all headland tracks are in the same direction but I don't think that causes the issue):

![missedturn](https://cloud.githubusercontent.com/assets/2379521/24832873/77429892-1c7f-11e7-902f-a2b1b8c8d61e.PNG)

**Comment by Satissis** [comment]
@pvajko no the headland directions do not have anything to do with it :)
This is next on my todo list to be fixed. Just not had the time lately to do much on cp, due to work.

**Comment by Satissis** [comment]
Should be fixed in v01.00117
Try it out and report back.

**Comment by pvajko** [comment]
Just to give a heads up, found my tractor slipping two fields away when working on Field 9 at Coldborough Farm, did not see what exactly happened but might have been this bug. I'm on 00119. 

Will keep an eye on it.

**Comment by pvajko** [comment]
Still seeing this:

![image](https://cloud.githubusercontent.com/assets/2379521/25259044/2ccc49f0-2609-11e7-96bc-5f462be42a47.png)

tractor continued straight into the next field. Let me know how can I help debugging this.

**Comment by pops64** [comment]
Debug channel 12 and 14 as well has what are your turn settings. And are you using headlands. And workwidth of course. And if you can reproduce this on a standard map. Save game and CP courses

**Comment by brnl** [comment]
Thanks for referring to this one. I have tried again, with channels 12 and 14: [log.txt](https://github.com/Courseplay/courseplay/files/988148/log.txt)
This logfile contains two runs: One with 1 headland. This works fine. The second run is with 2 headlands and that one fails. 

Course generation settings:
![image](https://cloud.githubusercontent.com/assets/3243133/25874968/5c3730a4-3515-11e7-9987-6cdb13a050f8.png)

The Turn settings are: 
![image](https://cloud.githubusercontent.com/assets/3243133/25874982/707395b2-3515-11e7-981b-430f1e780acc.png)

I am playing the stock map Sosnovka and the field is nr 14.
Save: [savegame3.zip](https://github.com/Courseplay/courseplay/files/988163/savegame3.zip)
Courses: [CoursePlay_Courses.zip](https://github.com/Courseplay/courseplay/files/988165/CoursePlay_Courses.zip)

**Comment by Timmiej93** [comment]
Here is my contribution to this issue:
Log: https://pastebin.com/VA8ywi5G
Enabled mods: https://pastebin.com/YpfTKMSy
Version: v5.01.00177
Map: LössHügelland v4.1

The log contains a run on a course that has been generated, saved, and then loaded (game has been exited inbetween). On this course, the tractor continued straight on at this point: 
![fsscreen_2017_08_05_14_50_22](https://user-images.githubusercontent.com/16491748/28995640-c89954e8-79ee-11e7-89e2-1b495a0ef07d.png)
![fsscreen_2017_08_05_14_50_45](https://user-images.githubusercontent.com/16491748/28995643-d44e50c2-79ee-11e7-9fe1-ed1a71fa642f.png)

I then deleted the course, and attempted to re-create it in the course generation window, which took a few tries, hence the multiple creations in the log. Creation settings:
![fsscreen_2017_08_05_14_52_48](https://user-images.githubusercontent.com/16491748/28995661-403c20de-79ef-11e7-9187-cbddf68ba486.png)

After this, I tried another run, and the same thing happened at the edge that's in the images above. I went to the other side of the field, which also has quite a sharp angle compared to the straight passes, thinking that that angle might have something to do with it, but on that side, it works fine:
![fsscreen_2017_08_05_15_02_43](https://user-images.githubusercontent.com/16491748/28995659-38f54206-79ef-11e7-8cc8-bc935c66d84c.png)

**Comment by pvajko** [comment]
If anyone can reproduce this, please post your courses and savegame as described in the last point in https://github.com/Courseplay/courseplay/wiki so we can fix it.

**Comment by pvajko** [comment]
Thanks for those who have posted a savegame and courses, that really helps.

To record the findings, the problem seems to be that sometimes when CP finds that the turn can be made on the headland (canTurnOnHeadland=true) it calculates the center of the questionmark turn as the turn could not be made on the headland, resulting in a positive centerHeightOffset (instead of negative) which puts the question mark behind the tractor.

**Comment by pvajko** [comment]
Made some more research on this. These are actually two different issues:

1. The one reported by @Timmiej93 is the one everyone else is having and this is when the turn can be made on the headland, the center of the question mark turn is calculated incorrectly, putting the turn behind the tractor. This is high priority as it happens with simple configurations like tractor + cultivator.

2. For the other one by @brnl at Sosnovska, the center of the question mark turn is also calculated incorrectly but this is because the tractor has an implement in front and one in back. If it has only one of the two, the turns work fine. Once number 1 is fixed, this needs to be retested and if still occurring, moved to a separate issue.

**Comment by pvajko** [comment]
Number 1 should be fixed now, for Number 2 a new issue is created: #2265.
