### ISSUE TITLE
about  turn point and  infinite circle

### ISSUE THREAD

**Issue by magicmana** [Courseplay/courseplay#2861]
hello 
some  in seed mode, and field mode  some tractors make infinite circle ,when the angle between,  Start point, and finish point, when  turn maneuver ; not near 90° (figure1)  but where is very large (figure2) or very small (figure 3).
![sans titre](https://user-images.githubusercontent.com/32802279/45164063-f32f5400-b1f1-11e8-89c2-4a7e88a8fed8.png)

like on this  video : 
https://www.youtube.com/watch?v=3iqLivr4HO0

some tractor are more sensitive  like : claas axion 900 mod
https://www.farming-simulator.com/mod.php?lang=fr&country=fr&mod_id=66111

but   have the same problem  with  standard  tractor  like puma cvx ,  although less often.

i make 10 try with the  Claas Axion : 
each time  he make a circle after entrance point .

i make 10 try with the Puma CVX 
each time   the entrance  point work , but
3 times out of 10 , i have a problem on the exit point ; the tractor miss the exit point and  go to  infinite circle.
2 short video : (working and not working)
https://www.youtube.com/watch?v=8qSscCkl5S4
https://www.youtube.com/watch?v=Ro_xufWeIE4

when i increase the circle range with a little collision  ,  the  tractor go out off infinite circle  : 
https://www.youtube.com/watch?v=WRRgIjwaG2M

I suppose that , the problem seems to be due to the value "Turning circle" which set automatically , in field and seed mode.

I guess it's not easy to remove accidental circles for only certain vehicles, while turns are used in all generated courses modes .
An   idea for resolve that   should to add 2 counters (one for start point and one for end point) for infinite circle during turn, if it's possible. 
Each time the counter  increased   you should   increase the default value "turning circle" for  1m too;   and after 5 or 10 try the tractor stop with error.  

--------

And now some news  about my personnal  scripts  i made 2 videos for my first real usage : creating refill courses . 
on the first i'm  create 2 shorts  courses,  to go and to back ,  to the nearest point, from my road network.
Then manually add the roads to the refill location.
(sorry for the poor quality , i have made some adjustment, in my screenshot soft,  since)
https://www.youtube.com/watch?v=avxE0NBFZxs

edit
i put a  screechoot of the course here , bbut, even with a screenshot, as the going and going are very close, it is not easy to see the contrast
![fsscreen_2018_09_06_22_18_53](https://user-images.githubusercontent.com/32802279/45184059-225fb880-b226-11e8-8695-30fc5a1998a8.png)

 

the second video is the result : 
https://www.youtube.com/watch?v=x4lGj6E_o1M

I still work on the speed adjustment ,  i have a not yet work  on the aggregation of  courses.
Actually i use the manual aggregate , and a modified pda_map_H.dds  in the maps mod. (since the first video)
Some time is not easy to find the order to aggregate, like on this sample ;  but I still win, already a lot of time.
With 6 seeder at the same time; before; I had not finished creating the 6 races manually, as the first one had already finished his field.

now I can create my 6 courses in 15 minutes for the fields closest to the refill location; and in 30 minutes if all my fields need complex road aggregation ,  to go to  the refill location.

**Comment by magicmana** [comment]
additional  screen  and  about  the circle problem : 

the course used for video  and the position 
![fsscreen_2018_09_06_21_22_28](https://user-images.githubusercontent.com/32802279/45184185-7e2a4180-b226-11e8-8a29-ebe2cd434d8d.png)

a sample from another course : 
- the course : 
![fsscreen_2018_09_06_21_30_58](https://user-images.githubusercontent.com/32802279/45184351-fee93d80-b226-11e8-9b72-a5f80de6a866.png)

- a turn  who work : 
![fsscreen_2018_09_06_21_35_53](https://user-images.githubusercontent.com/32802279/45184454-3c4dcb00-b227-11e8-922a-88111e180758.png)

-a  turn with a too smallest angle , and  infine circle  : 
![fsscreen_2018_09_06_21_39_01](https://user-images.githubusercontent.com/32802279/45184503-5d162080-b227-11e8-8723-290d35e0f794.png)

other information :  actually i  use  a 5.3.0 version ( downgrading,  due to the refill problem  since 5.3.7)

**Comment by pops64** [comment]
Leave pathfiding off to fix your refill problem I am guessing you are having. Has for the original issue bthe turn manuvers have always required fine adjustment to make some tools work correctly. Has it is not just the turning circle vaules that could cause wonky behavior. Eq the vanilla self propelled sprayer still is a hit or miss. And you provided two mods which most likely haven't had any of these adjustment. You can make there you self open up specialTools.lua and look at the other vehicles and how they are setup and make the adjustments. Then test them. Also the turning circle can be manually set. I can't remember how auto overrides a manual input but it should only occur once and that is on tool connect

**Comment by magicmana** [comment]
`And you provided two mods which most likely haven't had any of these adjustment.`
additional  information : 
the puma cvx and the trailer  ( bredal k165) are standard  stuff

`Also the turning circle can be manually set`

 I think actually  some  setting value are bypassed  in  seed mode.
for this case   the  "Combi mode settings" value  not working in  seed mode.
the  first think i do  was to change the  default value (14m with this trailer and tractor)  to 20m but , not extend the circle.


other sample in "Drive and work settings"  if i change "Tool offset vertical" for 0 to 5m front ;   the setting are bypassed  too : 
the tractor stop exactly at the same place.
![fsscreen_2018_09_07_02_43_51](https://user-images.githubusercontent.com/32802279/45192452-a9be2380-b248-11e8-94ef-f02d796d8d88.png)
![fsscreen_2018_09_07_02_44_29](https://user-images.githubusercontent.com/32802279/45192455-acb91400-b248-11e8-8197-bc106ba45652.png)

but  in  online documentation : 

**Tool offset vertical**

Only available in "overloader", "fertilizing/seeding", "field work", "combine self-unloading" and "liquid manure transporter" modes

**Comment by pops64** [comment]
Tool offset and waitpoint offset are not the same thing. Tool offset horzintal is to align the tool center to the course center while on the field. Off the field it is ingored. Waitpoint/Unload point offset is the vaule the changes where it parks at a wait point in the above picture it should move it under the pipe. It may not work in mode 4 has waitpoint loading was implemented in 17. Tool offset vertical is the vaule that is supposed to adjust where it stops at field edge in modes 4/6. Or at least it was suggested to include this. Turning circle is only for turning during field work(4/6) and turn manuvers. For modes 2/3 it is only used to leave the combine if it uses the improved turn

**Comment by magicmana** [comment]
Should be a good thing to   update the online documentation  ;-)
 on the website : 


**Tool offset horizontal**
...
This option lets you set this offset. It can also be used for filling / overloading points, to accommodate different vehicle sizes on the same course.
...


**Tool offset vertical**
...
Identical to the horizontal offset
...

**Comment by pops64** [comment]
Yeah the website is only 80% accurate

**Comment by magicmana** [comment]
hello , i set workTool.cp.direction.node.ZOffset  to 0.5 and  should resolve the problem

**Comment by pops64** [comment]
That's the other setting if turning circle doesn't fix things

**Comment by pops64** [comment]
Closed #2909
