### ISSUE TITLE
Anderson RBM2000 working/transport position

### ISSUE THREAD

**Issue by mxalbert** [Courseplay/courseplay#3516]
The Anderson RBM2000 bale collector doesn't switch to transport position (collector arm up) once it is full and the CP Helper turns to the transport course. Thus many obstacles are hit. When I stop the helper and try to move it to transport position manually I have to click 'b' twice, for the arm to move. However, once it is in the transport position, it drives to the tipping point, unloads fine, returns to the field and starts working normally.

I used version 162.

**Comment by pvaiko** [comment]
This should be working now, please reopen if it does not.

**Comment by SavageMkII** [comment]
I have tested with version 248, and this is still an issue. The bale loader arm stays down during transport to the unloading point.

**Comment by SavageMkII** [comment]
Bale loaders are working beautifully now! I tested both the Anderson ones and the Arcusin base game one.

Thanks @pvaiko! 

P.S. Your course generator is amazing! It blows my mind how good the courses it generates are.

**Comment by pvaiko** [comment]
@SavageMkII thanks!
