### ISSUE TITLE
Courseplay and System Tec Grass Dryer.

### ISSUE THREAD

**Issue by willdou8** [Courseplay/courseplay#4644]
I cannot for the life of me get Courseplay to recognize the unload trigger and the Grass Dryer. Not sure if it is my user error, by me not doing something correctly, but just looking for some advice as I have tried searching for answers but am coming up short. Thanks in advance.

This is the mod I am referring to: https://www.yesmods.com/fs19-mods/placeable-objects/silos/fs19-system-tec-grass-drying-fsm/

**Comment by Tensuko** [comment]
GlobalCompany ?
You need the Global Company 1.1.3.0 Version of it from GitHub so the GC Mods give the Trigger Information to CP.
Try it out and report, or post a logfile with debugchannel 1 and 2 active.

**Comment by suchna** [comment]
Got same problem with Fermenting Silo. And I have newest versions. If you tell me, which mode you need to track, I will try to make youtube video

**Comment by suchna** [comment]
Sorry, probably my mistake. I use GC from official FS19 site modhub and there's only version 1.1.1.0. I will answer later if it is still problem and post video in that case ;) 

And guys... Thank you for best mod in game ;) you rocks!

**Comment by Tensuko** [comment]
With GC 1.1.3+ it should work now.
If not let us know with log with channel 1 and 2.
Closed.

**Comment by suchna** [comment]
Yeah, sorry for not responding. Beeing bussy with christmas. I still have same problem, but my silo is not GC mod, whitch i realize sadly after updating GC. I Will test it after christmas and i will post you log to new topic if needed, but i am now thinking, that its not CP bug, but mods...  Merry christmas to you

**Comment by willdou8** [comment]
Still does not work with updated GC and updated Courseplay. 

Have no idea what you mean by posting log file with debug channel 1 and 2 active.
