### ISSUE TITLE
Issue on manure refill

### ISSUE THREAD

**Issue by masneoquil** [Courseplay/courseplay#6018]
Hello guys, I'm having an Issue since CP version 6.02.00050
I'm using CP to spread manure on a field and AD for the refill course. When it reaches the manure buying point, the buy screen opens and I can't close it, giving no choice but to force quit. I tested with and without adding a fill type on CP screen,
Currently I using version 53, but I did a test with version 49 and then version 50
If I use CP for refilling, it just go by without refilling. 

I made the test on a default map.

![Screen](https://user-images.githubusercontent.com/53353740/91907913-18d88200-ec81-11ea-95e6-26b89535f2bf.jpg)

[log.txt](https://github.com/Courseplay/courseplay/files/5158933/log.txt)

**Comment by Tensuko** [comment]
On what Trigger do you try to refill ?
Adding the FillType should be correct, but this window should not pop up.
Can you also make a logfile with debugchannel 2 active ?

**Comment by andreasthu** [comment]
Had the same issue a few days ago.
Are you using globalCompany?
Version 1.7 and higher is the problem.
Since i use 1.6.... it works normal.
Lg
Andreas

**Comment by Tensuko** [comment]
We had that Issue a while ago but it should be fixed, thats why I wonder why it pops up again.
Got to investigate it, maybe it is back for Mode4 refill.....

**Comment by masneoquil** [comment]
I'm using this trigger. I'm attaching the log with channel 2.
I will try with globalCompany 1.6.
[log.txt](https://github.com/Courseplay/courseplay/files/5162494/log.txt)

![Screen](https://user-images.githubusercontent.com/53353740/91987552-97c2ce80-ed04-11ea-896f-af2ea6c8eca9.jpg)

**Comment by masneoquil** [comment]
I did a test with only CP, AD and the manure trigger, but the issue is still there. :(

[log.txt](https://github.com/Courseplay/courseplay/files/5162572/log.txt)

**Comment by schwiti6190** [comment]
@masneoquil can you try this with the current version again ?

**Comment by masneoquil** [comment]
Tested!!! Everything working great!! Great work guys, thanks so much!!!
