### ISSUE TITLE
Mode 9 still does not work

### ISSUE THREAD

**Issue by Crinouche** [Courseplay/courseplay#6447]
Hello,

Unfortunately, Mode 9 still does not work.
The loader does not detect the trailer. He stops and does not move. If I put a bit of silage in the trailer after it works.
I have done the route several times and tried with different trailers, but it doesn't work.
For the log, look at the end
![PHOTO1](https://user-images.githubusercontent.com/36656729/101290239-3463a380-3801-11eb-99a2-18debc0c40e7.png)
![PHOTO2](https://user-images.githubusercontent.com/36656729/101290242-37f72a80-3801-11eb-9e4a-726cd7685e05.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5649392/log.txt)

**Comment by Tensuko** [comment]
What map is this ?
Can you post your course and savegame ?

**Comment by TobiHH78** [comment]
As per Log the Map is Eiersholt.

**Comment by Crinouche** [comment]
Hello,

This is the EIERSHOLT map available on the official FS website.
What do you mean by "post your course and savegame?"

**Comment by Tensuko** [comment]
Exactly what I mean.
Create a .zip file of your savegame folder and post it here.
Same for the Course, so I can check whats going up there.

As we can't reproduce this Error.

**Comment by Crinouche** [comment]
Here,
I hope this is what you need.
[Sauvegarde 1.zip](https://github.com/Courseplay/courseplay/files/5654298/Sauvegarde.1.zip)
[courseStorage0153.zip](https://github.com/Courseplay/courseplay/files/5654301/courseStorage0153.zip)
[log.txt](https://github.com/Courseplay/courseplay/files/5654302/log.txt)

**Comment by Tensuko** [comment]
Not the single course.
Just post the whole CourseFolder.

**Comment by Crinouche** [comment]
[courseEiersholt.zip](https://github.com/Courseplay/courseplay/files/5654459/courseEiersholt.zip)

**Comment by Crinouche** [comment]
[courseManager.zip](https://github.com/Courseplay/courseplay/files/5654468/courseManager.zip)

**Comment by Tensuko** [comment]
Try the following:
Activate the Course Editor (default ctrl+numpad0)
At your 3rd Waitpoint at the Trailer is a normal Waypoint after the Waitpoint.
Remove that one with (default) ctrl+5 and try it again.
It is working for me.
I might have to make a smal Wiki Entry for this Issue, as it can sometimes happen that this special Waypoint appears.

**Comment by Tensuko** [comment]
fixed Course for you, but check your own course 1st to see whats wrong :) 
[FS19_Eiersholt.Eiersholt.zip](https://github.com/Courseplay/courseplay/files/5654569/FS19_Eiersholt.Eiersholt.zip)
![fsScreen_2020_12_07_19_40_04](https://user-images.githubusercontent.com/27344744/101391129-304c8a00-38c4-11eb-91e3-d6093eac6a74.png)
`<waypoint31 speed="0" angle="-9.48" pos="861.66 40.21 -496.78" wait="1"/>
    <waypoint32 speed="0" angle="170.56" pos="861.66 40.21 -496.78"/> <- This waypoint`

**Comment by Crinouche** [comment]
So I tested my own route by deleting the waypoint that was after the 3rd waiting point, but it still does not work.
Then I used the route you sent me, but this doesn't work either. Have you tested with the different trailers and several times in a row? because I feel like it works once in a while.
Thank you for your help

**Comment by Tensuko** [comment]
Just the trailer wich was there and the fact it is working makes me kinda sure you have a modconflict... Maybe REA mod ?

**Comment by Crinouche** [comment]
what is a REA mod? so that I can search

**Comment by Tensuko** [comment]
Nevermind you don't have REA installed.
I have no idea whats happening, it would help if you test your mods if any of them cause the Issue and best is, if you try to reproduce this Error on a Basegame Map with only Basegame equipment.

**Comment by Crinouche** [comment]
I removed all mods, but here's what's happening now.
I do not know what to do
[log.txt](https://github.com/Courseplay/courseplay/files/5658651/log.txt)

**Comment by Tensuko** [comment]
I am not sure if that Map does require some Mods to work.
Mod by Mod is the only way so far... ofc will do some more tests on my own when I got time, but all I did so far was working.

@schwiti6190 do you have any Idea why that couldn't work ?
I tested that savegame and it was all fine...

**Comment by TobiHH78** [comment]
Well, a short look on the Modhub shows, that the Map don`t require any additional mods...

https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=180514

From the Map description: 
You don't need any additional mods when playing on Eiersholt, but the map is compatible with:
- Seasons 19 by Realismus Modding (No additional GEO is needed. Eiersholt has a build in GEO)
- HorseExtension by the Farming Agency
- Strawharvest Addon by Creative Mesh
- AnimalPenExtension by GtX
- Manure system by Wopster

**Comment by Tensuko** [comment]
We can ping that back and forward now, fact is, the Mode is working from my tests and even on your savegame.

Why is it not working for you ?
I don't know.
Why is your savegame not working or even map with new savegame, when you removed so many mods ?
I don't know.

All you can do is try to figure out and if you noticed something strange, you can let us know and we can see if we can do something to improove or fix it.

**Comment by Crinouche** [comment]
Thank you and I appreciate all the efforts you are making to try to find a solution.
For the moment, the only solution I have found is to revert to the courseplay version 6.02.00045. with this version the shovel works, but i don't have access to updates.
thank you for your work

**Comment by Tensuko** [comment]
Did you try to reset your Wheelloader and see if it is working then with newest Version ?

**Comment by Crinouche** [comment]
> Avez-vous essayé de réinitialiser votre Wheelloader et voir s'il fonctionne avec la dernière version?

I just downloaded the latest version 6.03. 00015. I have reset my excavator, but it still does not work.
I have also tried with other excavators, but here too it works every other time
I also redid the course!

**Comment by Tensuko** [comment]
I have no Idea why it is not working for you... rly....
We had a testsave to get stuff working and I can sure tell you that this mode does what it should and I can't tell you right now why it is not working for you...
Try to make a logfile with debugchannel 10 active and post that one, but as I tested your savegame and it was working, the only guess I can make is any of your mods make a problem with CP Mode9...

**Comment by Tensuko** [comment]
Pretty sure Mod Conflict, Mod Issue, or anything corrupted.
Mode9 tested several times in several situations and not found a problem in CP.

**Comment by Crinouche** [comment]
Hello,

After hours of looking for my problem, I finally found the error.
Sorry Tensuko, but for me, it's not a mod conflict issue as I removed all mods and reset the vehicle folder.
I use AD for transport.
At the start of the game, when the first trailer arrives to load, I start the bucket and it fills it with no problem. Once the first trailer is full, it leaves and the second trailer arrives to load. And this is where the error occurs: If the bucket is empty, it will fill and empty without problem to the 2nd trailer, but if there is a little silage left in the bucket (photo1), it will go to fill, but will stop and not detect the trailer. If I manually empty the bucket into the trailer, and restart CP, the bucket will work normally, but if I empty the bucket into the bunker and restart CP(photo2), it won't work. The bucket stops again (photo3). I have to empty the contents of the bucket in the trailer for it to work again
![1](https://user-images.githubusercontent.com/36656729/102867335-e8d40b00-4438-11eb-9548-a33e32f0c8cb.png)
![2](https://user-images.githubusercontent.com/36656729/102867358-eec9ec00-4438-11eb-892a-136ccc2a1e0e.png)
![3](https://user-images.githubusercontent.com/36656729/102867368-f25d7300-4438-11eb-949b-71591e181407.png)
[log.txt](https://github.com/Courseplay/courseplay/files/5728682/log.txt)

**Comment by Tensuko** [comment]
@Crinouche 
Okay this is helpful, thank you, will investigate that.

**Comment by Tensuko** [comment]
Try with Version 6.03.00018 and report
https://github.com/Courseplay/courseplay/releases

**Comment by Crinouche** [comment]
OK, I'm doing that as soon as possible, but for now I don't have a bunker to empty.

**Comment by Crinouche** [comment]
Hello,
I updated this morning, but the problem remains the same: If there is silage left in the bucket before it goes to fill, it will not recognize the trailer.
I even have another problem with the new version. After emptying silo 1, with route 1, I program route 2 to empty silo 2, but the bucket systematically returns to route 1. It seems that route 1 has not been deleted?
Besides, I don't understand and I don't know what the new function is for in mode 9?

**Comment by schwiti6190** [comment]
@Crinouche Hi there are you up for some testing with a diffrent branch ? You would have to download this branch "David" and put it in your save and of course test it :)

**Comment by Crinouche** [comment]
Yes of course. Give me the download link. But I have to warn you, I'm not good at computers, so you have to be very clear in your explanations :)

**Comment by schwiti6190** [comment]
[courseplay_beta.zip](https://github.com/Courseplay/courseplay/files/5801918/courseplay_beta.zip)
You could use this file, but I would recommand only using it to test mode 9 as there a few changes to diffent drivers also on there, that haven't been completly tested :)

**Comment by Crinouche** [comment]
I just quickly tested this version, in my current game (by only testing mode 9) and the problem is the same: If the bucket is not empty before going to load, it will not recognize the next trailer .
I'll do some more testing, as soon as possible, without mod, with photos debugging channel ... and I'll get back to you.

**Comment by Crinouche** [comment]
I downloaded your Courseplay version and tested in my part only mode 9.
I removed all mods.
I deleted the "XML vehicles" file from my backup.
I recreated the charger run (photo1) but I still have the same problem. I even have another problem that just popped up.

problem 1: the loader must be empty before going to reload so that it recognizes the 2nd trailer, otherwise it stops. (photo 2) This is the problem we have been talking about for several days
Problem 2: when the 1st trailer is full (CASE 100% full), it goes away (photo 3) but the loader does not back up if there is a lot of silage in its bucket. It hangs there !? the 2nd tractor cannot move forward (J Deere) (photo 4)

[log.txt](https://github.com/Courseplay/courseplay/files/5808199/log.txt)

![image](https://user-images.githubusercontent.com/36656729/104444057-8d102400-5597-11eb-9b71-a51b8ab2e051.png)
![image](https://user-images.githubusercontent.com/36656729/104444099-9bf6d680-5597-11eb-809c-4ffcec8b60e4.png)
![image](https://user-images.githubusercontent.com/36656729/104444118-a44f1180-5597-11eb-9590-0b7e2532ec3f.png)
![image](https://user-images.githubusercontent.com/36656729/104444134-ab761f80-5597-11eb-98cf-8975a17ef633.png)

**Comment by schwiti6190** [comment]
@Crinouche Thanks a lot, this is really helpfull :) I will have a look at this problems :)

**Comment by Tensuko** [comment]
Try .00026 or higher and report

**Comment by Crinouche** [comment]
Hello,

_"problem 1: the loader must be empty before going to reload so that it recognizes the 2nd trailer, otherwise it stops. (photo 2) This is the problem we have been talking about for several days"_

I just tested the latest version. 6.03.00028. This problem appears to be resolved.
But others have appeared:
The loader rushes into the trailer.
The charger only charges on one side of the silo.

I will try to give you a more precise report, with photos, as soon as possible.

**Comment by alepinci** [comment]
> Hello,
> 
> _"problem 1: the loader must be empty before going to reload so that it recognizes the 2nd trailer, otherwise it stops. (photo 2) This is the problem we have been talking about for several days"_
> 
> I just tested the latest version. 6.03.00028. This problem appears to be resolved.
> But others have appeared:
> The loader rushes into the trailer.
> The charger only charges on one side of the silo.
> 
> I will try to give you a more precise report, with photos, as soon as possible.

Same here, the loader rushes into the trailer.

**Comment by Tensuko** [comment]
Can you try this:
Save the course, restart you savegame and try again.
I had a similar Issue with the Course unloading into BGA, but after a save restart it worked somehow.
After that, I even could create new course and it worked.
No Idea where it comes from

Another think I normaly do, when I saved the course, I edit it, as there is a 2nd Waypoint under the Waitpoint at my target and I remove this, not sure if this is also needed, haven't tried all combinations yet.

**Comment by Crinouche** [comment]
_Can you try this:
Save the course, restart you savegame and try again.
I had a similar Issue with the Course unloading into BGA, but after a save restart it worked somehow.
After that, I even could create new course and it worked.
No Idea where it comes from_
I just tried this, but it doesn't change anything for me.
The charger does anything. He jumps waitpoints, he rushes into the trailer. It only empties part of the silo if 2 silos are side by side ... etc.
![image](https://user-images.githubusercontent.com/36656729/105695253-2d543a00-5f02-11eb-8451-1b560967ee41.png)
![image](https://user-images.githubusercontent.com/36656729/105695282-35ac7500-5f02-11eb-9476-ee9450504920.png)
![image](https://user-images.githubusercontent.com/36656729/105695305-3cd38300-5f02-11eb-80df-30ccf55bc330.png)

**Comment by Tensuko** [comment]
For the last pic, check if there is something at the front of the silo, thats mostly the reason why he keep choose the same line over and over again.

About Trailers, will check whats going on, as I said, I had problems on the 1st time when use .00028 too, now its just fine...

**Comment by Crinouche** [comment]
_For the last photo, check if there is anything at the front of the silo, this is mainly why it keeps choosing the same line over and over again._

I checked this, before putting the photo and reporting it, otherwise I wouldn't have said anything !! This problem appears in all silos

**Comment by Tensuko** [comment]
And here does the problem start... I can't reproduce this anymore....
![fsScreen_2021_01_26_06_21_24](https://user-images.githubusercontent.com/27344744/105803962-e36d6180-5f9e-11eb-9204-91f6daa5a4f8.png)

On my savegame I even unload in dual... (Trigger)
![fsScreen_2021_01_24_14_10_56](https://user-images.githubusercontent.com/27344744/105803998-f718c800-5f9e-11eb-9c00-32593530292f.png)

Before that, somehow this happened before and after some testing of older Version and back to 29, it was working then.
![fsScreen_2021_01_23_19_32_59](https://user-images.githubusercontent.com/27344744/105804026-08fa6b00-5f9f-11eb-881c-0eb99ed4c882.png)

Ofc you need some distance to the waitpoint, but I try to find out what max distance.... I don't know why it became so picky....

**Comment by Tensuko** [comment]
okay... if too far away, it happens again
![fsScreen_2021_01_26_06_27_47](https://user-images.githubusercontent.com/27344744/105804266-a786cc00-5f9f-11eb-8981-f19c0d792fa9.png)

**Comment by Tensuko** [comment]
No Idea whats going on, here it is working just fine...
![fsScreen_2021_01_26_07_39_28](https://user-images.githubusercontent.com/27344744/105809343-cf7b2d00-5fa9-11eb-83a4-cd3c797c0be7.png)

**Comment by Tensuko** [comment]
Can you try if it is working for you now with Version 6.03.00042 ? The Driver will slow down when approaching the trailer.

**Comment by Crinouche** [comment]
I did some testing with version 6.03.0042. It seems to be working. I'll do some more testing and get back to you.

But now it's mode 10 which no longer works with version 042. :(

**Comment by Tensuko** [comment]
> But now it's mode 10 which no longer works with version 042. :(

I did test it and it was working fine, if you would give more info then this, we could have a look, but pls make a new Issue...
