### ISSUE TITLE
Exception, stopping Courseplay driver, 

### ISSUE THREAD

**Issue by TommyGFX** [Courseplay/courseplay#6636]
[log.txt](https://github.com/Courseplay/courseplay/files/5777498/log.txt)

2021-01-06 18:21 :17 [info lp556810] Optum 300 CVX (#2): Exception, stopping Courseplay driver, C:/Users/rico-/OneDrive/Dokumente/My Games/FarmingSimulator2019/mods/FS19_Courseplay/BunkersiloManager.lua:227: attempt to index local 'fillUnit' (a nil value)

**Comment by Tensuko** [comment]
And when did that Error came up ?

**Comment by TommyGFX** [comment]
Das kommt wenn ein Traktor das Silo verdichtet und ein anderer ankommt.

**Comment by Tensuko** [comment]
Try .00026 or higher and report

**Comment by Tensuko** [comment]
Fixed, mache hier zu.

**Comment by RayzerSharpe** [comment]
I'm running version (v6.03.00039). and this error is still happening.  The portion of the log file that is probably of interest is below. 

2021-02-14 17:37 :16 [info lp244142] Puma 185 CVX (#2): not in a good position to unload, trying to recover
2021-02-14 17:37 :16 [info lp244142] Puma 185 CVX (#2): dx = 10.24, dz = 9.20, offset = 8.77, sameDir = false
2021-02-14 17:38 :54 [info lp250034] Puma 185 CVX (#2): Waypoint index 1165 reset to 226
2021-02-14 17:38 :54 [info lp250034] Puma 185 CVX (#2): AI driver in mode 2 starting at 10/226 waypoints (COURSEPLAY_NEXT_POINT)
2021-02-14 17:38 g_combineUnloadManager:getHasUnloaders(vehicle):false
2021-02-14 17:42 LUA call stack:
2021-02-14 17:42   =C:/Users/Home/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/base.lua (714) : printCallstack
2021-02-14 17:42   =C:/Users/Home/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineUnloadManager.lua (120) : __index
2021-02-14 17:42   =C:/Users/Home/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineUnloadManager.lua (252) : getUnloaderIndex
2021-02-14 17:42   =C:/Users/Home/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineUnloadManager.lua (188) : getCombineWithMostFillLevel
2021-02-14 17:42   =C:/Users/Home/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineUnloadAIDriver.lua (332) : giveMeACombineToUnload
2021-02-14 17:42   =C:/Users/Home/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineUnloadAIDriver.lua (220) : driveOnField
2021-02-14 17:42   =C:/Users/Home/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/AIDriver.lua (406) : drive
2021-02-14 17:42   =[C] (4294967295)
2021-02-14 17:42   =C:/Users/Home/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/base.lua (714) : xpcall
2021-02-14 17:42   dataS/scripts/vehicles/SpecializationUtil.lua (30)
2021-02-14 17:42   dataS/scripts/vehicles/Vehicle.lua (1306) : raiseEvent
2021-02-14 17:42   dataS/scripts/network/NetworkNode.lua (98) : update
2021-02-14 17:42   dataS/scripts/network/Server.lua (58) : updateActiveObjects
2021-02-14 17:42   dataS/scripts/BaseMission.lua (1500) : update
2021-02-14 17:42   dataS/scripts/FSBaseMission.lua (1979) : update
2021-02-14 17:42   dataS/scripts/missions/mission00.lua (469) : update
2021-02-14 17:42   dataS/scripts/main.lua (1944) : update
2021-02-14 17:42 :26 [info lp262700] Puma 185 CVX (#2): Exception, stopping Courseplay driver, C:/Users/Home/Documents/My Games/FarmingSimulator2019/mods/FS19_Courseplay/CombineUnloadManager.lua:120: attempt to index a nil value

My log file is clear except for 1 error i have on another vehicle which is as follows. In this example i changed the tractor to the Case 185 and it too stopped (As above). I'm trying to sort out the error below

2021-02-14 17:19 SelectedCombineToUnloadSetting:init()
2021-02-14 17:19   Warning (C:/Users/Home/Documents/My Games/FarmingSimulator2019/mods/FS19_Valtra_Hitech/Valtra.xml): I3D file offers '3' objects, but '2' components have been loaded!
